---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    - EAI_SCENARIO=2.18
    - EAI_SCENARIO=3.0
    - EAI_SCENARIO=stable
    - EAI_SCENARIO=beta
    - EAI_SCENARIO=canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EAI_SCENARIO=canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl pi.dk/3/ | bash # gnu parallel

install:
  - ./scripts/change-ember-cli-version.sh

script:
  - yarn lint
  - yarn test
